# Generated by Django 2.2.6 on 2020-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete='', to='dabba.canteenItems')),
            ],
        ),
    ]
